title: Optimization Method
repository: https://github.com/Michxz312/Optimization-Problems
branch: main
jupyter:
  nbconvert_template_paths:
    - _layouts/
  use_jupyter_lab_nbconvert: true
  notebook_path: _toc.yml
